dist: trusty
sudo: false

language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

go_import_path: bramp.net/goredirects

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci